version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=challenge      
    ports:
      - "5432:5432"
    networks:
      - network_postgres
    volumes:
      - postgres:/var/lib/postgresql/data  
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "gui@alura.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "54321:80"
    networks:
      - network_postgres
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: 128M

volumes:
  postgres:

networks:
  network_postgres:
    driver: bridge